<?php include('inc/navBar.php'); ?>
	
    <div id = "etWrap">
    	<div id = "etInWrap">
        	<h1 style = "font-size: 3em;">Final Ethics Project by Christopher Munroe</h1>
            <br /><br />
        	<h1>Racism in Europe</h2>
            	<p>All ethnic groups are subject to unfair prejudice. With Europe's ever-changing economic circumstances, racism emerges across the continent. When a country experiences financial hardship, the general population often develops hatred towards its immigrants. <a class = "round_putin" href = "http://www.rferl.org/content/russia-world-cup-football-soccer-racism-2018/26956948.html"><img src = "http://i.imgur.com/6OcodAm.png" alt = "Racism Nazi image"/></a>The general population would rather pass the blame. This minority-scapegoating results in radical political parties encouraging racist ideologies. Trapped in a corner, many cling to these right-wing political philosophies in hopes of a better world. If a society is in shambles, people are willing to try anything to rebuild their lives, even if it involves stomping out another's. In the midst of the Great Depression, even the Nazi party came to power. This process is the main reason for the relentless discrimination that is still rampaging throughout Europe today.</p>
            <br /><br  />
    		<h2>Rise of Neo-Nazism in Russia</h2>
            <p>In 2006, Amnesty International, an organization focused on human rights, reported that "<a href = "https://www.amnesty.org/en/documents/EUR46/022/2006/en/">Racist attacks and killings of foreigners and ethnic minorities are regularly reported in Russia.</a>" With recent Neo-Nazi activity in the realm of soccer, it is evident that Russia has not found a solution to their growing problem. According to the <a href = "http://www.farenet.org/wp-content/uploads/2015/02/SOVA-monitoring-report.pdf#page=8">Time for Action report</a>, there have been more than 200 racist and discriminatory incidents from 2012 to 2014. <iframe id = "emman_vid" width="460" height="315" src="https://www.youtube.com/embed/_8NvC0CyEwo?start=7" frameborder="0" allowfullscreen></iframe>Emmanuel Frimpong, a partcipant in the Russian Premier League match, was Russia's most recent victim. After a red card was raised, Frimpong claims to be <a href = "http://www.dailymail.co.uk/sport/sportsnews/article-3170953/Emmanuel-Frimpong-banned-two-games-sticking-middle-finger-Spartak-Moscow-fans-alleged-racist-abuse.html">subject to monkey chants from the crowd</a>. The player reacted with an offensive gesture and recieved a two game ban for his actions. The accused fans were not punished. A member of Fare Network, an organization against inequality in football, says, "<a href = "http://www.theguardian.com/football/2015/jul/25/racism-row-russia-world-cup-draw">How the Frimpong case was dealt with shows that denial is still the answer of Russian authorities when they are confronted with racist incidents</a> ..." Russian authorities are contributing to the problem by ignoring it. As the host of the 2018 World Cup, hopefully Russia can tame their crowds in time.</p>
		<h1>MalcolmX Application</h1>
		<p>The human-rights activist, MalcomX, had an aggressive approach to the racism African-Americans of his time were subjected to. His famous speech, "<a href = "http://www.cis.aueb.gr/Besides%20Security/TALKS/TALKS-10-X%20%28The%20Ballot%20or%20the%20Bullet%29.pdf">The Ballot or the Bullet</a>," encourages people of color to take action. If African-Americans tolerate unequal treatment, they will continue to recieve unequal treatment, Malcolm argues. He points out that, "<a href = "http://www.cis.aueb.gr/Besides%20Security/TALKS/TALKS-10-X%20(The%20Ballot%20or%20the%20Bullet).pdf#page=7">Historically, revolutions are bloody</a>." To bring about change, the backers have to get angry. He is urging his audience to react passionately to the injustice that surrounds them. <a class = "round_putin" style = "float: right; margin-right: 0;" href = "https://en.wikipedia.org/wiki/Malcolm_X"><img src = "http://i.imgur.com/KvBnurR.jpg" alt = "MALCOLM IMAGE"/></a>Malcolm  states, "<a href = "">I'm nonviolent with those who are nonviolent with me. But when you drop that violence on me, then you've made me go insane, and I'm not responsible for what I do. And that's the way every Negro should get</a>." He encourages an eye for an eye attitude to put the perpetrator in their place. If a person treats you as a subordinate being, you must remind them otherwise.</p> 
        <p>Malcolm's political philosophy may be able to guide these players to an equitable playing field. Black football players must react agressively while weilding the media as their tool in their fight for fair treatment. If Russian authorities are allowed to sweep these incidents under the rug, progress towards equality will remain at a stand still. Bringing publicity to this social issue will force Russia to tame their audiences. Players like Frimpong are fed up with the demeaning chants and are alerting the world to it. Frimpong is reciprocating the actions of his biased audiences. Unacceptable behavior must be equally matched.</p>
		<h1>Martin Luther King Application</h1>
		<p>Martin Luther King's nonviolent civil disobedient approach contrasts greatly with MalcomX's radical methods. Luther led countless peaceful protests to raise awareness, and create "tension." MLK says that, "<a href = "http://www.africa.upenn.edu/Articles_Gen/Letter_Birmingham.html">Nonviolent direct action seeks to create such a crisis and foster such a tension that a community which has constantly refused to negotiate is forced to confront the issue</a>." <a class = "round_putin" href = "https://en.wikipedia.org/wiki/Martin_Luther_King,_Jr."><img src = "http://i.imgur.com/BZi9q8W.jpg" alt = "MLK IMAGE"/></a>Tension is the key factor in a protest because it is what drives negotiation. The seminal <a href = "https://en.wikipedia.org/wiki/Montgomery_Bus_Boycott">Montgomery Bus Boycott</a> establishes the effectiveness of Luther's nonviolent approach. Unwilling parties are pressured to negotiate and compromise.</p>   
		<p>Luther combatted racial inequality through acts of civil disobedience. By employing MLK's methods, the realm of football could stomp out this very same problem. The players must not act as Frimpong did. Anger only creates enemies, while complacency only facilitates injustice. Players must adopt a composed and defiant attitude. MLK would see this as a perfect opportunity for a boycott. With this nonviolent direct action, Russia would experience a crisis. Teams that decline their invitations out of disobedience would be the gadflies that spur Russia into motion. Without this tension, Russia would have no incentive to solve the problem. The gentle pressuring created by a boycott evokes progress while still encouraging both parties to end on good terms.</p>
	</div>
    </div>

    
