<?php include('inc/navBar.php'); ?>
	
    <div id = "etWrap">
    	<div id = "etInWrap">
        	<h1>Racism in Europe</h2>
            	<p>All ethnic groups are subject to unfair prejudice. With Europe's ever-changing economic circumstances, racism emerges across the continent. When a country experiences financial hardship, the general population often develops hatred towards its immigrants. The general population would rather pass the blame. This minority-scapegoating results in radical political parties encouraging racist ideologies. Trapped in a corner, many cling to these right-wing political philosophies in hopes of a better world. If a society is in shambles, people are willing to try anything to rebuild their lives, even if it involves stomping out another's. In the midst of the Great Depression, even the Nazi party came to power. This process is the main reason for the relentless discrimination that is still rampaging throughout Europe today.</p>
    		<h2>Rise of Neo-Nazism in Russia</h2>
            	<p>In 2006, Amnesty International, an organization focused on human rights, reported that "<a href = "https://www.amnesty.org/en/documents/EUR46/022/2006/en/">Racist attacks and killings of foreigners and ethnic minorities are regularly reported in Russia.</a>" With recent Neo-Nazi activity in the realm of soccer, it is evident that Russia has not found a solution to their growing problem. According to the <a href = "http://www.farenet.org/wp-content/uploads/2015/02/SOVA-monitoring-report.pdf#page=8">Time for Action report</a>, there have been more than 200 racist and discriminatory incidents from 2012 to 2014. <iframe id = "emman_vid" width="460" height="315" src="https://www.youtube.com/embed/_8NvC0CyEwo?start=7" frameborder="0" allowfullscreen></iframe>Emmanuel Frimpong, a partcipant in the Russian Premier League match, was Russia's most recent victim. After a red card was raised, Frimpong claims to be <a href = "http://www.dailymail.co.uk/sport/sportsnews/article-3170953/Emmanuel-Frimpong-banned-two-games-sticking-middle-finger-Spartak-Moscow-fans-alleged-racist-abuse.html">subject to monkey chants from the crowd</a>. The player reacted with an offensive gesture and recieved a two game ban for his actions. The accused fans were not punished. A member of Fare Network, an organization against inequality in football, says, "<a href = "http://www.theguardian.com/football/2015/jul/25/racism-row-russia-world-cup-draw">How the Frimpong case was dealt with shows that denial is still the answer of Russian authorities when they are confronted with racist incidents</a> ..." Russian authorities are contributing to the problem by ignoring it. As the host of the 2018 World Cup, hopefully Russia can tame their crowds.</p>
		<h1>MalcolmX's Application</h1>
		<p>The human-rights activist, MalcomX, had an aggressive approach to the racism African-Americans of his time were subjected to. His famous speech, "<a href = "http://www.cis.aueb.gr/Besides%20Security/TALKS/TALKS-10-X%20%28The%20Ballot%20or%20the%20Bullet%29.pdf">The Ballot or the Bullet</a>," encourages African-Americans to take action. </p>        
	</div>
    </div>

    
